# Start tmux automatically if not already inside tmux
if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
  tmux attach -t default || tmux new -s default
fi

# :q behaves like exit terminal
:q() {
  exit
}

# create alias for vim
alias vim="nvim"
